---
- name: Update all Debian nodes
  hosts: cluster_nodes 
  become: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Perform a full upgrade of all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: true

    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system if needed
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists
